"""empty message

Revision ID: 9ab82a637ea9
Revises: bd001b1393dd
Create Date: 2019-09-04 21:08:28.820228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ab82a637ea9'
down_revision = 'bd001b1393dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile')
    op.add_column('puzzle', sa.Column(
        'default_size', sa.Integer(), nullable=False))
    op.add_column('puzzle', sa.Column(
        'extension', sa.String(), nullable=False))
    op.alter_column('puzzle', 'image',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'image',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('puzzle', 'extension')
    op.drop_column('puzzle', 'default_size')
    op.create_table('tile',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('puzzle_id', postgresql.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('position', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('image', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['puzzle_id'], ['puzzle.id'], name='tile_puzzle_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='tile_pkey')
                    )
    # ### end Alembic commands ###
